import type { MenuItem, Testimonial, PromoBanner, RestaurantInfo } from './types';

export const restaurantInfo: RestaurantInfo = {
  name: 'Flor do Maracujá',
  tagline: 'Cozinha Regional com Sabor de Casa',
  about: 'Há mais de 15 anos servindo o melhor da culinária regional brasileira com receitas passadas de geração em geração. Aqui, cada prato conta uma história de amor, tradição e sabores autênticos que aquecem o coração.',
  address: 'Av. Mal. Mascarenhas de Morais, 4715 - Imbiribeira, Recife - PE, 51150-004',
  phone: '(81) 3456-7890',
  whatsapp: '5581987654321',
  instagram: '@flordomaracuja21',
  coordinates: {
    lat: -8.112930,
    lng: -34.913680,
  },
  hours: [
    { day: 'Segunda a Sexta', open: '11:00', close: '15:00' },
    { day: 'Segunda a Sexta', open: '18:00', close: '22:00' },
    { day: 'Sábado', open: '11:00', close: '16:00' },
    { day: 'Sábado', open: '18:00', close: '23:00' },
    { day: 'Domingo', open: '11:00', close: '16:00' },
  ],
};

export const mockMenuItems: MenuItem[] = [
  // Pratos Principais
  {
    id: '1',
    name: 'Moqueca de Camarão',
    description: 'Deliciosa moqueca capixaba com camarões frescos, leite de coco, dendê e temperos especiais. Acompanha arroz branco e pirão.',
    price: 89.90,
    category: 'Pratos Principais',
    image: 'https://images.unsplash.com/photo-1762305194194-6896afafecb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller', 'spicy'],
    available: true,
  },
  {
    id: '2',
    name: 'Picanha na Chapa',
    description: 'Suculenta picanha grelhada na perfeição, acompanhada de arroz, feijão tropeiro, farofa crocante e vinagrete.',
    price: 79.90,
    category: 'Pratos Principais',
    image: 'https://images.unsplash.com/photo-1663213990116-a43ddb308859?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  {
    id: '3',
    name: 'Feijoada Completa',
    description: 'Tradicional feijoada brasileira servida com arroz, couve refogada, farofa, laranja e torresmo.',
    price: 65.90,
    category: 'Pratos Principais',
    image: 'https://images.unsplash.com/photo-1705313381636-672463bfa6fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  {
    id: '4',
    name: 'Baião de Dois',
    description: 'Arroz com feijão verde, queijo coalho, carne de sol desfiada e temperos nordestinos. Prato tradicional do sertão.',
    price: 54.90,
    category: 'Pratos Principais',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['new'],
    available: true,
  },
  {
    id: '5',
    name: 'Peixe na Telha',
    description: 'Filé de peixe grelhado servido em telha de barro com legumes salteados, batatas e molho de alcaparras.',
    price: 72.90,
    category: 'Pratos Principais',
    image: 'https://images.unsplash.com/photo-1762305194194-6896afafecb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
  
  // Entradas
  {
    id: '6',
    name: 'Bolinho de Bacalhau',
    description: 'Tradicionais bolinhos de bacalhau crocantes servidos com molho de pimenta especial da casa (6 unidades).',
    price: 32.90,
    category: 'Entradas',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  {
    id: '7',
    name: 'Pastel de Queijo com Goiabada',
    description: 'Pastéis artesanais recheados com queijo minas e goiabada cascão. Combinação perfeita! (4 unidades)',
    price: 24.90,
    category: 'Entradas',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
  {
    id: '8',
    name: 'Coxinha da Vovó',
    description: 'Coxinhas gigantes de frango com catupiry, receita especial da família (3 unidades).',
    price: 21.90,
    category: 'Entradas',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  
  // Bebidas
  {
    id: '9',
    name: 'Suco de Maracujá Natural',
    description: 'Suco refrescante de maracujá natural feito na hora (500ml).',
    price: 12.90,
    category: 'Bebidas',
    image: 'https://images.unsplash.com/photo-1768077499787-761c5f3cbe5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  {
    id: '10',
    name: 'Açaí na Tigela',
    description: 'Açaí cremoso com banana, granola, mel e frutas da estação (400ml).',
    price: 18.90,
    category: 'Bebidas',
    image: 'https://images.unsplash.com/photo-1602234382521-610b2abf9029?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
  {
    id: '11',
    name: 'Caipirinha Tradicional',
    description: 'Caipirinha clássica de limão, cachaça artesanal e açúcar.',
    price: 16.90,
    category: 'Bebidas',
    image: 'https://images.unsplash.com/photo-1602234382521-610b2abf9029?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
  
  // Sobremesas
  {
    id: '12',
    name: 'Pudim de Leite Condensado',
    description: 'Pudim cremoso da casa com calda de caramelo (fatia generosa).',
    price: 14.90,
    category: 'Sobremesas',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    badges: ['bestseller'],
    available: true,
  },
  {
    id: '13',
    name: 'Mousse de Maracujá',
    description: 'Mousse leve e refrescante de maracujá com calda de frutas vermelhas.',
    price: 12.90,
    category: 'Sobremesas',
    image: 'https://images.unsplash.com/photo-1768077499787-761c5f3cbe5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
  {
    id: '14',
    name: 'Bolo de Fubá com Goiabada',
    description: 'Tradicional bolo de fubá caseiro com pedaços de goiabada. Acompanha café coado.',
    price: 11.90,
    category: 'Sobremesas',
    image: 'https://images.unsplash.com/photo-1675106643937-791e74751488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    available: true,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Maria Silva',
    rating: 5,
    comment: 'A moqueca é simplesmente divina! Me lembrou a comida da minha avó. Lugar aconchegante e atendimento maravilhoso!',
    date: '2026-01-15',
    approved: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
  {
    id: '2',
    name: 'João Pedro Santos',
    rating: 5,
    comment: 'Melhor feijoada da região! Já virei cliente fiel. O tempero é perfeito e as porções são generosas.',
    date: '2026-01-28',
    approved: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joao',
  },
  {
    id: '3',
    name: 'Ana Carolina',
    rating: 5,
    comment: 'Ambiente familiar, comida caseira de verdade! A picanha estava no ponto perfeito. Super recomendo!',
    date: '2026-02-02',
    approved: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
  },
  {
    id: '4',
    name: 'Carlos Eduardo',
    rating: 4,
    comment: 'Ótima experiência! Os bolinhos de bacalhau são incríveis. Só achei que poderia ter mais opções vegetarianas.',
    date: '2026-02-05',
    approved: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
  },
];

export const mockPromoBanners: PromoBanner[] = [
  {
    id: '1',
    title: 'Promoção da Semana',
    description: 'Moqueca de Camarão com 15% de desconto! Válido de segunda a quinta-feira.',
    image: 'https://images.unsplash.com/photo-1762305194194-6896afafecb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    active: true,
    validUntil: '2026-02-13',
  },
  {
    id: '2',
    title: 'Feijoada de Sábado',
    description: 'Todo sábado tem feijoada especial com sobremesa incluída!',
    image: 'https://images.unsplash.com/photo-1705313381636-672463bfa6fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    active: true,
  },
  {
    id: '3',
    title: 'Happy Hour',
    description: 'De segunda a sexta, das 17h às 19h - Caipirinhas com preço especial!',
    image: 'https://images.unsplash.com/photo-1602234382521-610b2abf9029?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    active: true,
  },
];
